config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
	root 'home#index'

    get '/404' ,to: redirect('/404') , as: 'not_found'
    get '/422', to: redirect('/422'), as: 'change'
    get '/500', to: redirect('/500')

  resources :users do
    resources :following, only: :index
    resources :followers, only: :index
  end
  get "/profile/:id", to: "users#profile", as: "profile"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  resources :posts
  resources :comments
  get "/new" => "posts#new"
  post "/new" => "posts#create"
  get "show/:id" => "posts#show", as: 'post_show'
  post "search" => "posts#search"
  resources :follows, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :load_like, only: :destroy

  def create
    @like = Like.find_or_initialize_by post_id: params[:post_id],
      user_id: current_user.id
    if @like.save
    end
  end

  def destroy
    @like.destroy
  end

  private
  def load_like
    @like = Like.find_by id: params[:id]
  end
end

app/views/likes/_like.html.erb
<a onclick="<%= "like('#{likes_path post_id: post.id}');" %>" class="btn btn-xs">
  <%= t :like %>
</a>

app/views/likes/_unlike.html.erb
<a onclick="<%= "like('#{like_path like}', 'delete')" %>" class="btn btn-xs">
  <%= t :unlike %>
</a>

app/views/likes/create.js.erb
$('#likes-<%= "#{@like.post.id}" %>').html(
  '<%= @like.post.likes.size %>'
);
$('#like-<%= "#{@like.post.id}" %>').html(
  '<%= j render "likes/unlike", like: @like %>'
);

app/views/likes/destroy.js.erb
$('#likes-<%= "#{@like.post.id}" %>').html(
  '<%= @like.post.likes.size %>'
);
$('#like-<%= "#{@like.post.id}" %>').html(
  '<%= j render "likes/like", post: @like.post %>'
);