config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
	root 'home#index'

    get '/404' ,to: redirect('/404') , as: 'not_found'
    get '/422', to: redirect('/422'), as: 'change'
    get '/500', to: redirect('/500')

  resources :users do
    resources :following, only: :index
    resources :followers, only: :index
  end
  get "/profile/:id", to: "users#profile", as: "profile"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  resources :posts
  resources :comments
  get "/new" => "posts#new"
  post "/new" => "posts#create"
  get "show/:id" => "posts#show", as: 'post_show'
  post "search" => "posts#search"
  resources :follows, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :presence => true, :uniqueness => true, :length => { :in => 8..255 }
  has_many :posts
  has_many :comments
  has_many :likes
  has_many :favorite_posts, class_name: Post.name, through: :likes, source: :post
  has_many :active_follows,
    class_name: Follow.name,
    foreign_key: :follower_id,
    dependent: :destroy
  has_many :following, through: :active_follows,
    source: :followed
  has_many :passive_follows,
    class_name: Follow.name,
    foreign_key: :followed_id,
    dependent: :destroy
  has_many :followers, through: :passive_follows,
    source: :follower
  attr_accessor :protected_token
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}

  VALID_PHONE_REGEX = /[+]?[\d]+[^a..z][^A..Z][^\B]\z/
  validates :phone, presence: true,
    format: {with: VALID_PHONE_REGEX},
    length: {minimum: 6, maximum: 12},
    allow_nil: true

  has_secure_password
  validates :password, presence: true,
    length: {minimum: 6}, allow_nil: true

  before_save :format_value

  mount_uploader :avatar, PictureUploader

  scope :search_by_name, ->keyword {where "name LIKE ?", "%#{keyword}%"}

  class << self
    def new_token
      SecureRandom.urlsafe_base64
    end

    def digest string
      cost = BCrypt::Engine::MIN_COST
      BCrypt::Password.create string, cost: cost
    end
  end

  def authenticated? token
    return false if protected_digest.nil?
    BCrypt::Password.new(self.protected_digest).is_password? token
  end

  def remember
    self.protected_token = User.new_token
    update_attribute :protected_digest, User.digest(protected_token)
  end

  def forget
    self.update_attribute :protected_digest, nil
  end

  def is_user? other
    self == other
  end

  def follow other_user
    active_follows.create followed_id: other_user.id
  end

  def unfollow other_user
    active_follows.find_by(followed_id: other_user.id).destroy
  end

  def following? other_user
    following.include? other_user
  end

  private
    def format_value
      self.email = email.downcase
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:destroy, :edit, :update, :profile]
  before_action :load_user, except: [:new, :create, :index]
  before_action :correct_user, only: [:edit, :update, :profile]
  before_action :verify_admin, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:info] = t :wellcome, name: @user.name
      log_in @user
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    store_location
    @followers = @user.followers.search_by_name(params[:key]).per_page_kaminari params[:page]
    @following = @user.following.search_by_name(params[:key]).per_page_kaminari params[:page]
    if logged_in?
      @relationship = current_user.active_follows
        .find_or_initialize_by followed_id: @user.id
    end
  end

  def profile
  end

  def edit
      render :edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t :updated
      redirect_to root_url
    else
      render :edit
    end
  end

  def index
    @users = User.search(params[:key]).paginate page: params[:page],
      per_page: 16
  end

  def destroy
    unless @user.destroy
      flash[:warning] = t :failed, name: @user.name
      redirect_to users
    end
  end

  private
  def user_params
    params.require(:user).permit :name,
      :birthday, :email, :sex, :address,
      :phone, :password,
      :password_confirmation, :avatar
  end

  def correct_user
    unless current_user.is_user? @user
      flash[:danger] = t :user_not_correct
      redirect_to root_url
    end
  end

  def load_user
    @user = User.find_by id: params[:id]
    unless @user
      flash[:danger] = t :user_not_found
      redirect_to root_url
    end
  end
end

app/views/users/_follow.html.erb
<%= form_for @relationship, remote: true do |f| %>
  <%= hidden_field_tag :followed_id, @user.id %>
  <%= f.submit t(".follow"), class: "btn btn-primary form-control" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user%>
  <% if current_user.following? @user%>
    <%= render "unfollow" %>
  <% else %>
    <%= render "follow" %>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, html: { multipart: true } do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "Name" ,class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :birthday %>
    <%= f.date_field :birthday, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :sex %>
    <%= f.select :sex,
      options_for_select(
        [
          [t(:male), :male],
          [t(:female), :female],
          [t(:gay), :gay],
          [t(:lesbian), :lesbian]
        ], @user.sex
      ), {},
      class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, placeholder: "Address" , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, placeholder: "Phone" , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, placeholder: "Email" , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, placeholder: "Password" , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <div class="form-group">
    <span class="picture">
      <%= f.file_field :avatar %>
    </span>
  </div>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_profiletag.html.erb
 <div class="container">
<div class="form-horizontal">

	<div class="col-md-6 row">
	<!-- Form Name -->
	<legend>User profile form requirement
		<div class="pull-right">
			<small>
				<% if current_user? @user %>
					<%= link_to "Edit Profile", edit_user_path(:id=>current_user.id)%>
				<%  end %>
			</small>
		</div>
	</legend>

	<!-- Text input-->

	<div class="form-group row">
	 	<label class="col-md-4 control-label" for="email">Email: </label>
		<div class="col-md-8">
			<div class="input-group ">
				<div class="input-group-addon"><i class="fa fa-envelope-o"></i></div>
				<input  name="email" disabled="true" type="text" value="<%= @user.email %>" class="form-control input-md " >
			</div>
		</div>
	</div>

	<!-- Text input-->
	<div class="form-group row">
		<label class="col-md-4 control-label" for="name">Name: </label>
		<div class="col-md-8">
			<div class="input-group">
			   <div class="input-group-addon"><i class="fa fa-male" style="font-size: 20px;"></i></div>
			  <input  name="name" disabled="true" type="text" value="<%= @user.name %> " class="form-control input-md " >
			  </div>
		</div>
	</div>
	<!-- Text input-->
	<div class="form-group row">
		<label class="col-md-4 control-label" for="birthday">Birthday: </label>
		<div class="col-md-8">
			<div class="input-group">
			   <div class="input-group-addon"><i class="fa fa-birthday-cake"></i></div>
			  <input  name="birthday" disabled="true" type="text" value="<%= @user.birthday %>" class="form-control input-md " >
			  </div>

		</div>
	</div>
	<!-- Text input-->
	<div class="form-group row">
		<label class="col-md-4 control-label" for="sex">Sex: </label>
		<div class="col-md-8">
			<div class="input-group">
			   <div class="input-group-addon"><i class="fa fa-male" style="font-size: 20px;"></i></div>
			  <input  name="sex" disabled="true" type="text" value="<%= @user.sex %>" class="form-control input-md " >
			  </div>

		</div>
	</div>
	<!-- Text input-->
	<div class="form-group row">
		<label class="col-md-4 control-label" for="address">Address: </label>
		<div class="col-md-8">
			<div class="input-group">
			   <div class="input-group-addon"><i class="fa fa-sticky-note-o"></i></div>
			  <input  name="address" disabled="true" type="text" value="<%= @user.address %>" class="form-control input-md " >
			  </div>

		</div>
	</div>
	<!-- Text input-->
	<div class="form-group row">
		<label class="col-md-4 control-label" for="phone">Phone: </label>
		<div class="col-md-8">
			<div class="input-group">
			   <div class="input-group-addon"><i class="fa fa-birthday-cake"></i></div>
			  <input  name="phone" disabled="true" type="text" value="<%= @user.phone %>" class="form-control input-md " >
			  </div>

		</div>
	</div>
	</div>
	<div class="col-md-2 hidden-xs">
		<img src="<%= @user.avatar%>" class="img-responsive img-thumbnail" style="margin-bottom:20px;">		
	 </div>
</div>



</div>

app/views/users/_unfollow.html.erb
<%= form_for @relationship, html: { method: :delete }, remote: true do |f| %>
  <%= f.submit t(".unfollow"), class: "btn btn-default form-control" %>
<% end %>

app/views/users/_user.html.erb
<div class="col-md-3 col-xs-6" id="user_content_id_<%= user.id %>">
  <div class="row text-center">
    <% if user.avatar? %>
      <%= link_to image_tag(user.avatar, alt: "user.name", size: "100x100",
        class: "avatar"), user%>
    <% else %>
      <%= link_to image_tag("user-default.png", alt: user.name,
        size: "100x100", class: "avatar" ), user %>
    <% end %>
  </div>
  <div class="row text-center">
    <% if logged_in? && current_user != user %>
      <div class="row">
        <% if current_user.admin? %>
          <%= button_tag t(:delete),class: "btn btn-danger",
            onclick: "deleteUser('#{user.id}', '#{t(:confirm_delete,
            type: t(:user), name: user.name)}')" %>
        <% end %>
      </div>
    <% end %>
    <div class="row">
      <p><%= link_to user.name, user, class: "form-label" %></p>
      <p><%= user.birthday %></p>
      <p><%= user.sex %></p>
    </div>
  </div>
</div>

app/views/users/_user_info.html.erb
<div class="col-md-2 col-xs-12 text-center">
    <div class="form-group">
      <% if @user.avatar? %>
        <%= link_to image_tag(@user.avatar, alt: "@user.name", size: "130x130",
          class: "avatar"), @user %>
      <% else %>
        <%= link_to image_tag("user-default.png", alt: @user.name,
          size: "130x130", class: "avatar" ), @user %>
      <% end %>
    </div>
    <div class="form-group">
      <%= link_to user_following_index_path(@user), data: {turbolinks: false} do %>
        <strong id="following">
          <%= @user.following.count %>
        </strong>
          <%= t ".following" %>
      <% end %>
      <strong> | </strong>
      <%= link_to user_followers_path(@user), data: {turbolinks: false} do %>
        <strong id="followers">
          <%= @user.followers.count %>
        </strong>
          <%= t ".followers" %>
      <% end %>
    </div>
    <div class="form-group" id="follow_form">
      <%= render "users/follow_form" if logged_in? %>
    </div>
</div>
<div class="col-md-3 col-xs-12">
    <h3 class="user-name"><label><%=  @user.name %></label></h3>
    <h4><%= t ".birthday", birthday: @user.birthday %></h4>
    <h4><%= t ".address", address: @user.address %></h4>
</div>

app/views/users/_users.html.erb
<h1><%= yield(:header_title) %></h1>
<%= form_tag yield(:path_search), method: :get, id: "search_users" do %>
  <div class="row panel">
    <div class="input-group pull-right">
      <%= text_field_tag :key, params[:key], id: yield(:search_id),
        class: "form-control", placeholder: t(".placeholder") %>
      <div class="input-group-btn">
        <%= submit_tag t(:search), class: "btn btn-info" %>
      </div>
    </div>
  </div>
<% end %>
<hr>
<div class="alert alert-danger" id="connect_failed" hidden="true">
  <label >
    <%= t :failed_connection %>
  </label>
</div>
<div id="result_search_<%= yield(:type_follow) %>" class="row" >
  <div class= "row" >
    <% if users.any? %>
      <%= render users %>
    <% end %>
  </div>
  <% if users.any? %>
      <div class="row text-center" id="will_paginate">
        <%= paginate users %>
      </div>
    <% end %>

</div>

app/views/users/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".btn_text") %>
<h1><%= t ".update" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, "Users" %>
<% provide :header_title, t(".header_title") %>
<% provide :search_id, "search_user_box" %>
<% provide :path_search, users_path %>
<%= render "users" %>

app/views/users/index.js.erb
$('#result_search').html('<%= j render @users %>');
$('#will_paginate').html('<%= will_paginate %>');

app/views/users/new.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, "Sign Up" %>
<h1><%= t :signup %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/profile.html.erb
<% provide :title, "Profile" %>
<% provide :button_text, "Submit" %>
<div class="card hovercard" >
        <div class="card-background">
            <img class="card-bkimg" alt="" src="<%= current_user.avatar%>">
        </div>
        <div class="useravatar">
            <img alt="" src="<%= current_user.avatar%>">
        </div>
        <div class="card-info"> <span class="card-title"><%= current_user.name%></span>

        </div>
</div>
<div  class="panel btn-pref btn-group btn-group-justified " role="group" >

              <div class="tabnav">
                   <div class="btn-group btn-group-justified ">
                    <div class="btn-group" role="group" >
                        <button id="b1" type="button" class="btn-nav btn" href="#tab1" data-toggle="tab" >
                        <div class="visible" >Profile  <span class="glyphicon glyphicon-user" aria-hidden="true"> </span></div>
                         </button>
                      </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-nav" href="#tab2" data-toggle="tab" >
                         <div class="visible">Posts <span class="glyphicon glyphicon glyphicon-duplicate" aria-hidden="true"></span></div>
                        </button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-nav" href="#tab4" data-toggle="tab">

                        <div class="visible">Favorites <span class="glyphicon glyphicon-heart" aria-hidden="true"></span></div>
                        </button>
                    </div>
                  <div class="btn-group" role="group">
                    <button type="button" class="btn btn-nav" href="#tab3" data-toggle="tab">
                             <div class="visible">Folower <span class="glyphicon glyphicon-user" aria-hidden="true"></span></div>
                        </button>
                    </div>


                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-nav" href="#tab5" data-toggle="tab">
                             <div class="visible">Following <span class="glyphicon glyphicon glyphicon-user" aria-hidden="true"></span></div>
                        </button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-nav" href="#tab6" data-toggle="tab">
                            <div class="visible">Message <span class="glyphicon glyphicon-bell"  aria-hidden="true"></span></div>
                        </button>
                    </div>
                 </div>
              </div>
        <div  class="tab-content" style= "margin-top:10px; " >
              <div class="tab-pane panel  active" id="tab1"  >
                    <div class="row">
                          <div class="col-md-6 col-md-offset-1" style= "margin-top: 20px; margin-bottom: 20px;" id="edit">
                            <%= render "profiletag" %>
                          </div>
                    </div>
               </div>
               <div class="tab-pane panel " id="tab2" >
                           <div class="content-container clearfix">
                               <div class="col-md-12">
                                   <input type="search" placeholder="Search Post" class="form-control mail-search" />
                                   <ul class="mail-list">
                                    <% post = Post.all.where(user_id: current_user) %>
                                    <% post.each do |p| %>
                                        <li>
                                               <%= link_to post_show_path(:id => p.id) do %>
                                                <b class="mail-sender"><%= p.title %></b>
                                               <span class="mail-subject"> Posted on  <%= p.created_at.strftime("%F") %> at <%=p.created_at.strftime("%I:%M%p") %></span>
                                               <span class="mail-message-preview">You have ten more subscriptions click her...</span>
                                                <%end %>
                                       </li>
                                    <%end %>
                                    </ul>
                                    </div>
                           </div>
                </div>
                <div class="tab-pane panel " id="tab3" >
                </div>
                <div class="tab-pane panel fade in " id="tab4" >
                    <form role="form" class="form-inline" >
                        <h2> <br> ... Tab 4</h2>
                     </form>
                </div>
                <div class="tab-pane panel fade in " id="tab5" >
                    <form role="form" class="form-inline">
                        <h2> <br> ... Tab 5</h2>
                     </form>
                </div>
                <div class="tab-pane panel fade in " id="tab6" >
                    <form role="form" class="form-inline">
                        <h2> <br> ... Tab 6</h2>
                     </form>
                </div>
         </div>
      </div>
</div>
</div>

app/views/users/show.html.erb
<% provide :title, "Profile #{@user.name}" %>
<% provide :button_text, "Submit" %>
<div class="card hovercard" >
        <div class="card-background">
            <img class="card-bkimg" alt="" src="<%= @user.avatar%>">
        </div>
        <div class="useravatar">
            <%= show_avatar @user %>
        </div>

        <div class="card-info">
          <h2><%= @user.name%>  </h2>
        </div>

</div>
<div  class="panel btn-pref btn-group btn-group-justified " role="group" >

              <div class="tabnav">
                   <div class="btn-group btn-group-justified ">
                    <div class="btn-group" role="group" >
                        <button id="b1" type="button" class="btn-nav btn" href="#tab1" data-toggle="tab" >
                        <div class="visible" >Profile  <span class="glyphicon glyphicon-user" aria-hidden="true"> </span></div>
                         </button>
                      </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-nav" href="#tab2" data-toggle="tab" >
                         <div class="visible">Posts <span class="glyphicon glyphicon glyphicon-duplicate" aria-hidden="true"></span></div>
                        </button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-nav" href="#tab3" data-toggle="tab">

                        <div class="visible">Favorites <span class="glyphicon glyphicon-heart" aria-hidden="true"></span></div>
                        </button>
                    </div>
                  <div class="btn-group" role="group">
                    <button type="button" class="btn btn-nav" href="#tab4" data-toggle="tab">
                             <div class="visible">Folower <span class="glyphicon glyphicon-user" aria-hidden="true"></span></div>
                        </button>
                    </div>


                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-nav" href="#tab5" data-toggle="tab">
                             <div class="visible">Following <span class="glyphicon glyphicon glyphicon-user" aria-hidden="true"></span></div>
                        </button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-nav" href="#tab6" data-toggle="tab">
                            <div class="visible">Message <span class="glyphicon glyphicon-bell"  aria-hidden="true"></span></div>
                        </button>
                    </div>
                 </div>
              </div>
        <div  class="tab-content" style= "margin-top:10px; " >
              <div class="tab-pane panel  active" id="tab1"  >
                <div class="form-group" id="follow_form">
                  <%= render "users/follow_form" if logged_in? %>
                </div>
                    <div class="row">
                          <div class="col-md-6 col-md-offset-1" style= "margin-top: 20px; margin-bottom: 20px;" id="edit">
                            <%= render "profiletag" %>
                          </div>
                    </div>
               </div>
               <div class="tab-pane panel " id="tab2" >
                 <div class="content-container clearfix">
                     <div class="col-md-12">
                         <input type="search" placeholder="Search Post" class="form-control mail-search" />
                         <ul class="mail-list">
                          <% post = Post.all.where(user_id: @user) %>
                          <% post.each do |p| %>
                              <li>
                                     <%= link_to post_show_path(:id => p.id) do %>
                                      <b class="mail-sender"><%= p.title %></b>
                                     <span class="mail-subject"> Posted on  <%= p.created_at.strftime("%F") %> at <%=p.created_at.strftime("%I:%M%p") %></span>
                                     <span class="mail-message-preview">You have ten more subscriptions click her...</span>
                                      <%end %>
                             </li>
                          <%end %>
                          </ul>
                    </div>
                 </div>
                </div>
                <div class="tab-pane panel " id="tab3" >
                  <% @user.favorite_posts.each do |p| %>
                      <li>
                       <%= link_to post_show_path(:id => p.id) do %>
                        <b class="mail-sender"><%= p.title %></b>
                       <span class="mail-subject"> Posted on  <%= p.created_at.strftime("%F") %> at <%=p.created_at.strftime("%I:%M%p") %></span>
                       <span class="mail-message-preview">You have ten more subscriptions click her...</span>
                        <%end %>
                     </li>
                  <%end %>
                </div>
                <div class="tab-pane panel fade in " id="tab4" >
                    <% provide :search_id, "search_follows_box" %>
                    <% provide :path_search, user_followers_path(@user) %>
                    <% provide :type_follow, "followers" %>
                    <%= render "users/users", users: @followers %>
                </div>
                <div class="tab-pane panel fade in " id="tab5" >
                  <% provide :search_id, "search_follows_box" %>
                  <% provide :path_search, user_following_index_path(@user) %>
                  <% provide :type_follow, "following" %>
                  <%= render("users/users", users: @following) if @following%>
                </div>
                <div class="tab-pane panel fade in " id="tab6" >

                </div>
         </div>
      </div>
</div>
</div>