config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
	root 'home#index'

    get '/404' ,to: redirect('/404') , as: 'not_found'
    get '/422', to: redirect('/422'), as: 'change'
    get '/500', to: redirect('/500')

  resources :users do
    resources :following, only: :index
    resources :followers, only: :index
  end
  get "/profile/:id", to: "users#profile", as: "profile"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  resources :posts
  resources :comments
  get "/new" => "posts#new"
  post "/new" => "posts#create"
  get "show/:id" => "posts#show", as: 'post_show'
  post "search" => "posts#search"
  resources :follows, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]

end

app/views/layouts/_login.html.erb
<div class="modal fade" id="login-modal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          &times;
        </button>
        <h3 class="modal-title glyphicon glyphicon-user">
          <%= t :login %>
        </h3>
      </div>
      <div class="modal-body">
        <%= form_for :session, url: login_path do |f| %>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :remember_me, class: "checkbox inline",
              class: "control-label" do %>
              <%= f.check_box :remember_me %>
              <%= t ".remember_me" %>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.submit "Login",
              class: "btn btn-primary form-control" %>
            <p>
              <%= t ".new" %>
              <%= link_to "Sign Up", signup_path %>
            </p>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default"
          data-dismiss="modal">
          <%= t ".close" %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= url_for(action: 'index', controller: '/home') %>">Tourism Review </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

				</a></li>
            <li><a href="#about">HOT</a></li>
            <li><a href="#contact">Đặt hàng</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hỏi & Đáp <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Giảm giá</a></li>
                <li><a href="#">Miễn phí</a></li>
                <li><a href="#">Thanh toán</a></li>
                <li><a href="#">Hoạt động khác</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Ngoài ra</li>
                <li><a href="#">Liên kết</a></li>
                <li><a href="#">Thành viên</a></li>
                <li><a href="#">Ứng dụng</a></li>
              </ul>
            </li>
            <li>
            <%= form_tag("/search", method: "post", class: "navbar-form", html: { multipart: true }) do |f| %>
			        <div class="form-group" style="display:inline;">
                <div class="input-group" ">
                                <%= text_field_tag 'key' , nil , class: "form-control",required: true, maxlength: 20, placeholder: 'Search here', size: 40%>
			            <div class="input-group-btn">
                      <button class="btn btn-info" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                  </div>
			          </div>
			        </div>
                <% end%>
            </li>
          </ul>
        <ul class="nav navbar-nav navbar-right" >

        <% if logged_in? %>
          <li class="dropdown" >
            <a href="#"
              class="dropdown-toggle hear-item"
              data-toggle="dropdown"
              role="button"
              aria-haspopup="true" aria-expanded="false" >
              <i class="glyphicon glyphicon-user" ></i>
              <%= current_user.name %>
              <span class="caret" ></span>
            </a>
            <ul class="dropdown-menu" >
                  <li>
                    <%= link_to  current_user  do%>
                    <%=t :label, scope: [:users, :profile]%>
                    <%end%>
                  </li>
              <li>
                <%= link_to t(:logout), logout_path %>
              </li>
              <li role="separator" class="divider" ></li>
              <li class="dropdown-header" >
                <%= t :notifications %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to signup_path, class: "hear-item" do %>
              <i class="glyphicon glyphicon-edit" ></i>
              <%= t :signup %>
            <% end %>
          </li>
          <li>
            <%= link_to login_path,
              data: {toggle: "modal", target: "#login-modal"},
              class: "hear-item" do %>
              <i class="glyphicon glyphicon-log-in" ></i>
              <%= t :login %>
            <% end %>
          </li>
        <% end %>
      </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <%= render "layouts/login" unless logged_in? %>
    <div class="container" style="margin:60px 100px 0 100px;">
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message.html_safe,
          class: "alert alert-#{message_type}" %>
      <% end %>
    	<%= yield %>


    </div>
	<!-- Footer -->
        <footer >
            <div class="container text-center">
            <hr>
              <div class="row">
                <div class="col-lg-12">
                  <div class="col-md-3">
                    <ul class="nav nav-pills nav-stacked">
                      <li><a href="#">About us</a></li>
                      <li><a href="#">Blog</a></li>
                    </ul>
                  </div>
                  <div class="col-md-3">
                    <ul class="nav nav-pills nav-stacked">
                      <li><a href="#">Product for Mac</a></li>
                      <li><a href="#">Product for Windows</a></li>
                    </ul>
                  </div>
                  <div class="col-md-3">
                    <ul class="nav nav-pills nav-stacked">
                      <li><a href="#">Web analytics</a></li>
                      <li><a href="#">Presentations</a></li>
                    </ul>
                  </div>
                  <div class="col-md-3">
                    <ul class="nav nav-pills nav-stacked">
                      <li><a href="#">Product Help</a></li>
                      <li><a href="#">Developer API</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <hr>

              <div class="row">
                  <div class="col-lg-12">
                      <ul class="nav nav-pills nav-justified">
                          <li><a href="/">© 2013 Company Name.</a></li>
                          <li><a href="#">Terms of Service</a></li>
                          <li><a href="#">Privacy</a></li>
                      </ul>
                  </div>
              </div>
            </div>
        </footer>
   <%= debug(params) if Rails.env.development? %>
   <!%= debug(params) if Rails.env.development? %>
  </body>
</html>